import type { SqliteMigration } from "./types";

export const initialMigration: SqliteMigration = {
  version: 1,
  name: "current_schema_baseline",
  up(sqlite) {
    for (const statement of CURRENT_SCHEMA_STATEMENTS) sqlite.run(statement);
  }
};

const CURRENT_SCHEMA_STATEMENTS = [
  `CREATE TABLE conversations (id TEXT PRIMARY KEY NOT NULL, title TEXT NOT NULL, source_title TEXT, summary TEXT NOT NULL, model TEXT, owner_user_id TEXT, message_count INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`,
  `CREATE TABLE geogebra_documents (owner_scope_key TEXT NOT NULL, owner_user_id TEXT, id TEXT NOT NULL, title TEXT NOT NULL, mime_type TEXT NOT NULL, content_kind TEXT NOT NULL CHECK (content_kind = 'binary'), content BLOB NOT NULL, size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0 AND size_bytes <= 16777216), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, PRIMARY KEY (owner_scope_key, id))`,
  `CREATE TABLE conversation_messages (id TEXT PRIMARY KEY NOT NULL, conversation_id TEXT NOT NULL, role TEXT NOT NULL CHECK (role IN ('user', 'assistant')), content TEXT NOT NULL, created_at INTEGER NOT NULL, payload TEXT NOT NULL)`,
  `CREATE TABLE conversation_blackboard_entries (id TEXT PRIMARY KEY NOT NULL, conversation_id TEXT NOT NULL, key TEXT NOT NULL, category TEXT NOT NULL CHECK (category IN ('original_problem', 'givens', 'goal', 'math_analysis', 'construction_plan', 'canvas_state', 'assumptions', 'open_issues', 'failed_attempts', 'teaching_notes')), value TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('active', 'archived')), confidence INTEGER NOT NULL CHECK (confidence >= 0 AND confidence <= 1000), reason TEXT NOT NULL, source_message_id TEXT, source_tool_call_id TEXT, source_run_id TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, archived_at INTEGER)`,
  `CREATE TABLE agent_run_ledgers (run_id TEXT PRIMARY KEY NOT NULL, conversation_id TEXT NOT NULL, client_session_id TEXT, status TEXT NOT NULL CONSTRAINT agent_run_ledgers_status_ck CHECK (status IN ('running', 'succeeded', 'failed', 'cancelled')), revision INTEGER NOT NULL DEFAULT 0, model_provider TEXT NOT NULL, model_id TEXT NOT NULL, started_at INTEGER NOT NULL, completed_at INTEGER, payload TEXT NOT NULL, CONSTRAINT agent_run_ledgers_lifecycle_ck CHECK ((status = 'running' AND completed_at IS NULL) OR (status IN ('succeeded', 'failed', 'cancelled') AND completed_at IS NOT NULL)), CONSTRAINT agent_run_ledgers_timeline_ck CHECK (completed_at IS NULL OR completed_at >= started_at))`,
  `CREATE TABLE agent_error_events (event_id TEXT PRIMARY KEY NOT NULL, run_id TEXT NOT NULL, conversation_id TEXT, source TEXT NOT NULL CONSTRAINT agent_error_events_source_ck CHECK (source IN ('run', 'tool')), code TEXT NOT NULL, severity TEXT NOT NULL CONSTRAINT agent_error_events_severity_ck CHECK (severity IN ('warning', 'error')), message TEXT NOT NULL, model_provider TEXT, model_id TEXT, tool_call_id TEXT, tool_name TEXT, created_at INTEGER NOT NULL, payload TEXT NOT NULL)`,
  `CREATE TABLE problem_sources (id TEXT PRIMARY KEY NOT NULL, kind TEXT NOT NULL CHECK (kind IN ('geochat_benchmark_case', 'gaokao_source_collection', 'manual')), name TEXT NOT NULL, version TEXT NOT NULL, source_path TEXT, source_hash TEXT NOT NULL, imported_at INTEGER NOT NULL, raw_metadata TEXT NOT NULL)`,
  `CREATE TABLE problems (id TEXT PRIMARY KEY NOT NULL, source_id TEXT NOT NULL, source_item_id TEXT NOT NULL, title TEXT NOT NULL, prompt TEXT NOT NULL, answer TEXT, analysis TEXT, kind TEXT NOT NULL CHECK (kind IN ('math_problem', 'exploration', 'regression')), task_type TEXT NOT NULL CHECK (task_type IN ('draw', 'solve', 'explain', 'construct', 'diagnose', 'revise', 'mixed', 'animation')), question_type TEXT NOT NULL CHECK (question_type IN ('mcq', 'fill_blank', 'open_ended', 'curated')), paper TEXT, year TEXT, score INTEGER, category TEXT, difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')), visual_potential INTEGER NOT NULL CHECK (visual_potential IN (0, 1)), raw_payload TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`,
  `CREATE TABLE problem_tags (problem_id TEXT NOT NULL, tag TEXT NOT NULL)`,
  `CREATE TABLE problem_topics (problem_id TEXT NOT NULL, topic TEXT NOT NULL)`,
  `CREATE TABLE problem_sets (id TEXT PRIMARY KEY NOT NULL, slug TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, source_id TEXT NOT NULL, kind TEXT NOT NULL CHECK (kind IN ('curated', 'generated', 'imported', 'eval')), created_at INTEGER NOT NULL)`,
  `CREATE TABLE problem_set_items (set_id TEXT NOT NULL, problem_id TEXT NOT NULL, sort_order INTEGER NOT NULL)`,
  `CREATE TABLE problem_attempts (id TEXT PRIMARY KEY NOT NULL, problem_id TEXT NOT NULL, conversation_id TEXT NOT NULL, owner_user_id TEXT, run_id TEXT, status TEXT NOT NULL CHECK (status IN ('started', 'completed', 'failed')), model_provider TEXT, model_id TEXT, started_at INTEGER NOT NULL, completed_at INTEGER, user_rating INTEGER, notes TEXT, CONSTRAINT problem_attempts_lifecycle_ck CHECK ((status = 'started' AND completed_at IS NULL) OR (status IN ('completed', 'failed') AND completed_at IS NOT NULL)))`,
  `CREATE TABLE benchmark_runs (id TEXT PRIMARY KEY NOT NULL, owner_user_id TEXT, suite_id TEXT NOT NULL, suite_version TEXT NOT NULL, suite_hash TEXT NOT NULL, config_hash TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'failed', 'interrupted', 'cancelled')), total_cases INTEGER NOT NULL CHECK (total_cases >= 0), completed_cases INTEGER NOT NULL DEFAULT 0, passed_cases INTEGER NOT NULL DEFAULT 0, failed_cases INTEGER NOT NULL DEFAULT 0, config TEXT NOT NULL, metrics TEXT NOT NULL, evidence_refs TEXT NOT NULL, error TEXT, started_at INTEGER NOT NULL, completed_at INTEGER, CONSTRAINT benchmark_runs_case_counts_ck CHECK (completed_cases >= 0 AND passed_cases >= 0 AND failed_cases >= 0 AND completed_cases <= total_cases AND passed_cases + failed_cases <= completed_cases), CONSTRAINT benchmark_runs_lifecycle_ck CHECK ((status = 'running' AND completed_at IS NULL) OR (status IN ('completed', 'failed', 'interrupted', 'cancelled') AND completed_at IS NOT NULL)))`,
  `CREATE TABLE benchmark_case_results (id TEXT PRIMARY KEY NOT NULL, run_id TEXT NOT NULL, case_id TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('passed', 'failed', 'error', 'skipped')), score REAL CHECK (score IS NULL OR (score >= 0 AND score <= 1)), metrics TEXT NOT NULL, evidence_refs TEXT NOT NULL, error TEXT, started_at INTEGER, completed_at INTEGER NOT NULL, CONSTRAINT benchmark_case_results_timeline_ck CHECK (started_at IS NULL OR completed_at >= started_at))`,
  `CREATE TABLE unified_problem_sources (id TEXT PRIMARY KEY NOT NULL, requested_id TEXT, repo_id TEXT NOT NULL, group_name TEXT NOT NULL CHECK (group_name IN ('production', 'external', 'reasoning', 'evaluation')), commit_sha TEXT, license TEXT, local_dir TEXT, source_hash TEXT NOT NULL, imported_at INTEGER NOT NULL, raw_metadata TEXT NOT NULL)`,
  `CREATE TABLE unified_problem_records (id TEXT PRIMARY KEY NOT NULL, source_id TEXT NOT NULL, source_item_id TEXT, source_file TEXT NOT NULL, source_index INTEGER NOT NULL, source_split TEXT, dataset_id TEXT NOT NULL, group_name TEXT NOT NULL CHECK (group_name IN ('production', 'external', 'reasoning', 'evaluation')), modality TEXT NOT NULL CHECK (modality IN ('text', 'image', 'multimodal')), construction TEXT NOT NULL CHECK (construction IN ('open_ended', 'multiple_choice', 'fill_blank', 'worked_solution', 'reasoning_trace')), prompt TEXT NOT NULL, answer_final TEXT, answer_type TEXT CHECK (answer_type IN ('label', 'free_form', 'numeric', 'expression', 'multi_label', 'unknown')), subject TEXT, grade TEXT, difficulty TEXT, language TEXT, license TEXT, media_count INTEGER NOT NULL DEFAULT 0, choice_count INTEGER NOT NULL DEFAULT 0, record_payload TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`,
  `CREATE INDEX conversations_updated_at_idx ON conversations (updated_at)`,
  `CREATE INDEX conversations_owner_updated_at_idx ON conversations (owner_user_id, updated_at)`,
  `CREATE INDEX geogebra_documents_scope_updated_idx ON geogebra_documents (owner_scope_key, updated_at)`,
  `CREATE INDEX conversation_messages_conversation_idx ON conversation_messages (conversation_id, created_at)`,
  `CREATE UNIQUE INDEX conversation_blackboard_entries_conversation_key_uidx ON conversation_blackboard_entries (conversation_id, key)`,
  `CREATE INDEX conversation_blackboard_entries_lookup_idx ON conversation_blackboard_entries (conversation_id, status, category)`,
  `CREATE INDEX agent_error_events_run_id_idx ON agent_error_events (run_id, created_at)`,
  `CREATE INDEX agent_error_events_conversation_idx ON agent_error_events (conversation_id, created_at)`,
  `CREATE INDEX agent_error_events_source_idx ON agent_error_events (source, created_at)`,
  `CREATE INDEX agent_run_ledgers_recovery_idx ON agent_run_ledgers (client_session_id, status, started_at)`,
  `CREATE UNIQUE INDEX problems_source_item_uidx ON problems (source_id, source_item_id)`,
  `CREATE INDEX problems_search_idx ON problems (task_type, difficulty, visual_potential)`,
  `CREATE UNIQUE INDEX problem_tags_uidx ON problem_tags (problem_id, tag)`,
  `CREATE INDEX problem_tags_tag_idx ON problem_tags (tag)`,
  `CREATE UNIQUE INDEX problem_topics_uidx ON problem_topics (problem_id, topic)`,
  `CREATE INDEX problem_topics_topic_idx ON problem_topics (topic)`,
  `CREATE UNIQUE INDEX problem_sets_slug_uidx ON problem_sets (slug)`,
  `CREATE UNIQUE INDEX problem_set_items_uidx ON problem_set_items (set_id, problem_id)`,
  `CREATE INDEX problem_set_items_set_order_idx ON problem_set_items (set_id, sort_order)`,
  `CREATE INDEX problem_attempts_owner_idx ON problem_attempts (owner_user_id, started_at)`,
  `CREATE INDEX problem_attempts_problem_idx ON problem_attempts (problem_id, started_at)`,
  `CREATE INDEX benchmark_runs_owner_started_idx ON benchmark_runs (owner_user_id, started_at)`,
  `CREATE INDEX benchmark_runs_suite_started_idx ON benchmark_runs (suite_id, started_at)`,
  `CREATE UNIQUE INDEX benchmark_case_results_run_case_uidx ON benchmark_case_results (run_id, case_id)`,
  `CREATE INDEX benchmark_case_results_run_idx ON benchmark_case_results (run_id, completed_at)`,
  `CREATE UNIQUE INDEX unified_problem_sources_repo_uidx ON unified_problem_sources (repo_id, group_name)`,
  `CREATE INDEX unified_problem_sources_group_idx ON unified_problem_sources (group_name)`,
  `CREATE UNIQUE INDEX unified_problem_records_source_item_uidx ON unified_problem_records (source_id, source_file, source_index)`,
  `CREATE INDEX unified_problem_records_dataset_split_idx ON unified_problem_records (dataset_id, source_split)`,
  `CREATE INDEX unified_problem_records_group_idx ON unified_problem_records (group_name, dataset_id)`,
  `CREATE INDEX unified_problem_records_shape_idx ON unified_problem_records (construction, modality)`,
  `CREATE INDEX unified_problem_records_taxonomy_idx ON unified_problem_records (subject, grade)`
] as const;
