#!/usr/bin/env node
/**
 * Writes dist/_headers for Cloudflare Pages.
 *
 * Generated rather than committed because the CSP has to name the installer
 * mirror host, and this is a public repository that keeps deployment hosts out
 * of tracked files (see OPEN_SOURCE.md). The host comes from
 * VITE_DOWNLOADS_BASE, the same variable the site itself is built with, so the
 * policy and the code can never disagree about where downloads come from.
 *
 *   node scripts/write-headers.mjs
 */
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const dist = path.join(here, "..", "dist");

if (!existsSync(dist)) {
  console.error("write-headers: dist/ does not exist — run the build first");
  process.exit(1);
}

/** Origin of a URL, or null when unset or unparseable. */
function originOf(value) {
  if (!value) return null;
  try {
    return new URL(value).origin;
  } catch {
    console.warn(`write-headers: ignoring unparseable URL ${JSON.stringify(value)}`);
    return null;
  }
}

const mirrorOrigin = originOf(process.env.VITE_DOWNLOADS_BASE);

// The download page reads the mirror manifest first and the GitHub API second.
// Those are the only two cross-origin requests the whole site makes.
const connect = ["'self'", mirrorOrigin, "https://api.github.com"].filter(Boolean);

const csp = [
  "default-src 'self'",
  "script-src 'self'",
  // Inline style attributes are used for figure and stage transitions.
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "media-src 'self'",
  `connect-src ${connect.join(" ")}`,
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'none'",
  "object-src 'none'"
].join("; ");

const body = `# Generated by scripts/write-headers.mjs. Do not edit dist/ by hand.
#
# The CSP is tight because this site loads nothing from anywhere else: fonts
# are self-hosted and there are no analytics, tag managers or embeds.
${mirrorOrigin ? `# Installer mirror allowed in connect-src: ${mirrorOrigin}` : "# No installer mirror configured; connect-src allows only the GitHub API."}

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Permissions-Policy: geolocation=(), microphone=(), camera=(), interest-cohort=()
  Content-Security-Policy: ${csp}

# Content-hashed, so safe to cache forever.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable

# Stable filenames, so a week rather than a year.
/media/*
  Cache-Control: public, max-age=604800

# HTML must revalidate or a redeploy is invisible to returning visitors.
/*.html
  Cache-Control: public, max-age=0, must-revalidate

/
  Cache-Control: public, max-age=0, must-revalidate
`;

writeFileSync(path.join(dist, "_headers"), body, "utf8");
console.log(
  `write-headers: wrote dist/_headers (connect-src: ${connect.join(" ")})`
);
